sms:
  aliyun:
    enabled: true
  tencent:
    enabled: false

spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: debug

customer:
  name: alibaba
  valid-period: 365d
  contract:
    name: tom
    phone: 15824135598
report:
  sendByEmail: true
  emailSubject: report issue
  recipient: 52jinchao@163.com

#debug: true
#trace: true