

spring:
  datasource:
    url: jdbc:h2:file:~/learn-springboot-data-h2-db
    username: sa
    password: sa
    #type: org.h2.jdbcx.JdbcDataSource

  h2:
    console:
      enabled: true
      path: /h2-console
  jdbc:
    template:
      max-rows: 100
      fetch-size: 1
      query-timeout: 3s
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  redis:
    password: 12345
    port: 6379
    host: 192.168.33.10
    lettuce:
      pool:
        enabled: true
        max-wait: 1s
  cache:
    type: redis
    redis:
      key-prefix: redisCache-
      enable-statistics: true
      time-to-live: 10s
      use-key-prefix: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 5
    local-cache-scope: session

logging:
  level:
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: debug
    com.example.learn.springboo.data.repository.impl: trace
    org.mybatis: trace