

spring:
  datasource:
    url: jdbc:h2:file:~/learn-springboot-data-h2-db
    username: sa
    password: sa
    #type: org.h2.jdbcx.JdbcDataSource

  h2:
    console:
      enabled: true
      path: /h2-console
  jdbc:
    template:
      max-rows: 100
      fetch-size: 1
      query-timeout: 3s
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: debug
    com.example.learn.springboo.data.repository.impl: trace